#!/bin/bash
#
# Copyright 2014 Facundo Batista

set -eu
export PYTHONPATH=yaswfp

if [ $# -ne 0 ]; then
    TARGET="$@"
else
    TARGET="."
fi

nosetests3 -v -s $TARGET
flake8 $TARGET
rm -rf __pycache__
